
import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tress Idehen
 */
public class NewJFrame extends javax.swing.JFrame {
    
    
    int Questionnaire_Location = 1;
    int Current_Point;
    int Total_Points;
    
    String Question_1 = "When making a decision, you rely more on your feelings than on analysis of the situation";
    String Question_2 = " You prefer to act immediately rather than speculate about various options";
    String Question_3 = "You are inclined to rely more on improvisation than on prior planning";
    String Question_4 = " You often contemplate the complexity of life";
    String Question_5 = "You frequently and easily express your feelings and emotions";
    String Question_6 = " You tend to sympathize with other people";
    String Question_7 = "You tend to rely on your experience rather than on theoretical alternatives";
    String Question_8 = " You are strongly touched by the stories about people's troubles";
    String Question_9 = "For you, it is easier to gain knowledge through hands-on experience than from books or manuals";
    String Question_10 = "You have good control over your desires and temptations";
    
    String User_Role_Type;
    String User_Personality_Type;
    String user_16_personality_type;
    
    String Diplomats;//My Role Types
    String Sentinels;
    String Analysts;
    String Explorers;
    
    String Advocates;//My Diplomats Personality Types
    String Mediators;
    String Protagonists;
    String Campaigners;
    
    String Logisticians;//My Sentinels Personality Types
    String Defenders;
    String Executives;
    String Consuls;
    
    String Architects;//My Analysts Personality Types
    String Logicians;
    String Commanders;
    String Debaters;
    
    String Virtuosos;//My Adventurers Personality Types
    String Adventurers;
    String Entrepreneurs;
    String Entertainers;
    
    
    
    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {//the constructor
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user_answer = new javax.swing.ButtonGroup();
        Window_Content = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        avatar = new javax.swing.JLabel();
        First_Name = new javax.swing.JLabel();
        Last_Name = new javax.swing.JLabel();
        input_first_name = new javax.swing.JTextField();
        input_last_name = new javax.swing.JTextField();
        verify_user = new javax.swing.JButton();
        Separator = new javax.swing.JSeparator();
        welcome_user = new javax.swing.JLabel();
        user_fullname = new javax.swing.JLabel();
        begin_test_button = new javax.swing.JButton();
        begin_test_button.setVisible(false);
        Introduction = new javax.swing.JPanel();
        Separator_Instructions = new javax.swing.JSeparator();
        Instruction_Label = new javax.swing.JLabel();
        Begin_Test_Button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        Questions = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        button_list = new javax.swing.JPanel();
        button1 = new javax.swing.JPanel();
        Button1 = new javax.swing.JButton();
        Question_Title = new javax.swing.JLabel();
        Question_Number = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();
        ProgressPercentage = new javax.swing.JLabel();
        Total_Score = new javax.swing.JLabel();
        Question_List = new javax.swing.JPanel();
        Question1 = new javax.swing.JLabel();
        Question2 = new javax.swing.JLabel();
        Question3 = new javax.swing.JLabel();
        Question4 = new javax.swing.JLabel();
        Question5 = new javax.swing.JLabel();
        Question6 = new javax.swing.JLabel();
        Question7 = new javax.swing.JLabel();
        Question8 = new javax.swing.JLabel();
        Question9 = new javax.swing.JLabel();
        Question10 = new javax.swing.JLabel();
        user_response = new javax.swing.JPanel();
        strongly_disagree = new javax.swing.JRadioButton();
        disagree = new javax.swing.JRadioButton();
        indifferent = new javax.swing.JRadioButton();
        agree = new javax.swing.JRadioButton();
        strongly_agree = new javax.swing.JRadioButton();
        Role_Type_Calculator = new javax.swing.JPanel();
        Get_Total_Point = new javax.swing.JButton();
        congratulations = new javax.swing.JLabel();
        instructions2 = new javax.swing.JLabel();
        advocate = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mediator = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        protagonist = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campaigner = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        logistician = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        defender = new javax.swing.JPanel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        executive = new javax.swing.JPanel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        consul = new javax.swing.JPanel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        architect = new javax.swing.JPanel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        logician = new javax.swing.JPanel();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        commander = new javax.swing.JPanel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        debater = new javax.swing.JPanel();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        virtuoso = new javax.swing.JPanel();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        adventurer = new javax.swing.JPanel();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        entrepreneur = new javax.swing.JPanel();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        entertainer = new javax.swing.JPanel();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("16 Personality Test");
        getContentPane().setLayout(new java.awt.CardLayout());

        header.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        header.setText("Welcome To The 16 Personalities Test.\n Please Enter The Following:");

        avatar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tress Idehen\\Documents\\NetBeansProjects\\PersonalityTest\\images\\default-avatar.png")); // NOI18N
        avatar.setToolTipText("Click To Select Avatar");
        avatar.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.black));
        avatar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                avatarMouseClicked(evt);
            }
        });

        First_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        First_Name.setText("First Name");
        First_Name.setToolTipText("First Name");

        Last_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Last_Name.setText("Last Name");
        Last_Name.setToolTipText("Last Name");

        input_first_name.setToolTipText("Enter Your First Name Here");
        input_first_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NameTypeCheck(evt);
            }
        });

        input_last_name.setToolTipText("Enter Your Last Name Here");
        input_last_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                input_last_nameKeyTyped(evt);
            }
        });

        verify_user.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        verify_user.setText("VERIFY");
        verify_user.setToolTipText("Click Here To Verify You Info");
        verify_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verify_userActionPerformed(evt);
            }
        });

        welcome_user.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        welcome_user.setToolTipText("Me");

        user_fullname.setToolTipText("You");

        begin_test_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        begin_test_button.setText("BEGIN TEST >>");
        begin_test_button.setToolTipText("Click Here To Initiate Test");
        begin_test_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                begin_test_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Window_ContentLayout = new javax.swing.GroupLayout(Window_Content);
        Window_Content.setLayout(Window_ContentLayout);
        Window_ContentLayout.setHorizontalGroup(
            Window_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Window_ContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Window_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Separator)
                    .addComponent(header, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Window_ContentLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(welcome_user, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(Window_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(user_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(begin_test_button, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 88, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Window_ContentLayout.createSequentialGroup()
                        .addComponent(avatar)
                        .addGap(18, 18, 18)
                        .addGroup(Window_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(First_Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Last_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Window_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_first_name)
                            .addComponent(input_last_name)
                            .addGroup(Window_ContentLayout.createSequentialGroup()
                                .addComponent(verify_user, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        Window_ContentLayout.setVerticalGroup(
            Window_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Window_ContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Window_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Window_ContentLayout.createSequentialGroup()
                        .addGroup(Window_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(First_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_first_name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Window_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Last_Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(input_last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(verify_user, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Window_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(welcome_user, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(user_fullname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addComponent(begin_test_button, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        getContentPane().add(Window_Content, "card2");

        Instruction_Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Instruction_Label.setText("INSTRUCTIONS:");
        Instruction_Label.setToolTipText("");
        Instruction_Label.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        Begin_Test_Button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Begin_Test_Button.setText("BEGIN>>");
        Begin_Test_Button.setToolTipText("Click Only After You Have Read Instructions");
        Begin_Test_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Begin_Test_ButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setAutoscrolls(true);

        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextPane1.setText("The Scope of The Test Is Quite Simple Actually:\nThere are a total of 64 questions; the general encouragement is that you answer each one of them, truthfully to the best of your ability. The more honest you are with your answer, the more accurate will the result be.\nFew things to keep in mind regarding the Interface, you cannot return to a previously answered question, so make sure all answers are finalized before clicking on the next button.\nAfter the completion of the test, you will receive two separate results; one indicative of your Role Type in which there is solely a total of four, and from that role type there will be a character type as well, a list of four within each role as well.\nLet the test begin!!!\n");
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout IntroductionLayout = new javax.swing.GroupLayout(Introduction);
        Introduction.setLayout(IntroductionLayout);
        IntroductionLayout.setHorizontalGroup(
            IntroductionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IntroductionLayout.createSequentialGroup()
                .addGroup(IntroductionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IntroductionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Separator_Instructions))
                    .addGroup(IntroductionLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(Instruction_Label)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IntroductionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Begin_Test_Button)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IntroductionLayout.createSequentialGroup()
                .addGap(0, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        IntroductionLayout.setVerticalGroup(
            IntroductionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IntroductionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Instruction_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Separator_Instructions, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Begin_Test_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(Introduction, "card3");

        Questions.setToolTipText("");

        button_list.setLayout(new java.awt.CardLayout());

        Button1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Button1.setText(">>");
        Button1.setToolTipText("Click For Next Question");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout button1Layout = new javax.swing.GroupLayout(button1);
        button1.setLayout(button1Layout);
        button1Layout.setHorizontalGroup(
            button1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button1Layout.createSequentialGroup()
                .addComponent(Button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        button1Layout.setVerticalGroup(
            button1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Button1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
        );

        button_list.add(button1, "card2");

        Question_Title.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Question_Title.setText("QUESTION:");

        Question_Number.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Question_Number.setToolTipText("Question#");

        ProgressBar.setToolTipText("Your Progress Report");
        ProgressBar.setStringPainted(true);

        ProgressPercentage.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        Total_Score.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        Question_List.setLayout(new java.awt.CardLayout());

        Question1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Question_List.add(Question1, "card6");

        Question2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Question_List.add(Question2, "card6");

        Question3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Question_List.add(Question3, "card6");

        Question4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Question_List.add(Question4, "card6");

        Question5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Question_List.add(Question5, "card6");

        Question6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Question_List.add(Question6, "card6");

        Question7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Question_List.add(Question7, "card6");

        Question8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Question_List.add(Question8, "card6");

        Question9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Question_List.add(Question9, "card6");

        Question10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Question_List.add(Question10, "card6");

        user_answer.add(strongly_disagree);
        strongly_disagree.setText("I Strongly Disagree");
        strongly_disagree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strongly_disagreeActionPerformed(evt);
            }
        });

        user_answer.add(disagree);
        disagree.setText("I Disagree");
        disagree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disagreeActionPerformed(evt);
            }
        });

        user_answer.add(indifferent);
        indifferent.setText("I Am Indifferent");
        indifferent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indifferentActionPerformed(evt);
            }
        });

        user_answer.add(agree);
        agree.setText("I Agree");
        agree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agreeActionPerformed(evt);
            }
        });

        user_answer.add(strongly_agree);
        strongly_agree.setText("I Strongly Agree");
        strongly_agree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strongly_agreeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout user_responseLayout = new javax.swing.GroupLayout(user_response);
        user_response.setLayout(user_responseLayout);
        user_responseLayout.setHorizontalGroup(
            user_responseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
            .addGroup(user_responseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(user_responseLayout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(strongly_disagree)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(disagree)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(indifferent)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(agree)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(strongly_agree)
                    .addContainerGap(77, Short.MAX_VALUE)))
        );
        user_responseLayout.setVerticalGroup(
            user_responseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
            .addGroup(user_responseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(user_responseLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addGroup(user_responseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(strongly_disagree)
                        .addComponent(disagree)
                        .addComponent(indifferent)
                        .addComponent(agree)
                        .addComponent(strongly_agree))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout QuestionsLayout = new javax.swing.GroupLayout(Questions);
        Questions.setLayout(QuestionsLayout);
        QuestionsLayout.setHorizontalGroup(
            QuestionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuestionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QuestionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProgressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuestionsLayout.createSequentialGroup()
                        .addGroup(QuestionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(QuestionsLayout.createSequentialGroup()
                                .addComponent(jSeparator2)
                                .addGap(577, 577, 577))
                            .addGroup(QuestionsLayout.createSequentialGroup()
                                .addComponent(ProgressPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(166, 166, 166)
                                .addComponent(Question_Title)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Question_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                                .addGroup(QuestionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(button_list, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Total_Score, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuestionsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(user_response, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(QuestionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(QuestionsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Question_List, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        QuestionsLayout.setVerticalGroup(
            QuestionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuestionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(QuestionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Question_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Question_Number, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProgressPercentage, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(Total_Score, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                .addComponent(user_response, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_list, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(QuestionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuestionsLayout.createSequentialGroup()
                    .addContainerGap(144, Short.MAX_VALUE)
                    .addComponent(Question_List, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(158, Short.MAX_VALUE)))
        );

        getContentPane().add(Questions, "card4");

        Get_Total_Point.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Get_Total_Point.setText("RESULT");
        Get_Total_Point.setToolTipText("");
        Get_Total_Point.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Get_Total_PointActionPerformed(evt);
            }
        });

        congratulations.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        congratulations.setText("Congratulations On Completing The Test!!");
        congratulations.setToolTipText("");

        instructions2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        instructions2.setText("Click the Below Button\nTo Proceed to Your Result.");

        javax.swing.GroupLayout Role_Type_CalculatorLayout = new javax.swing.GroupLayout(Role_Type_Calculator);
        Role_Type_Calculator.setLayout(Role_Type_CalculatorLayout);
        Role_Type_CalculatorLayout.setHorizontalGroup(
            Role_Type_CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Role_Type_CalculatorLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(Role_Type_CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Role_Type_CalculatorLayout.createSequentialGroup()
                        .addComponent(Get_Total_Point, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132))
                    .addGroup(Role_Type_CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(instructions2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(congratulations)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        Role_Type_CalculatorLayout.setVerticalGroup(
            Role_Type_CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Role_Type_CalculatorLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(congratulations, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(instructions2, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Get_Total_Point, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        getContentPane().add(Role_Type_Calculator, "card5");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tress Idehen\\Documents\\NetBeansProjects\\PersonalityTest\\images\\advocate.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("You Are An: ADVOCATE");

        javax.swing.GroupLayout advocateLayout = new javax.swing.GroupLayout(advocate);
        advocate.setLayout(advocateLayout);
        advocateLayout.setHorizontalGroup(
            advocateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advocateLayout.createSequentialGroup()
                .addGroup(advocateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(advocateLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addGroup(advocateLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(advocateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))))
                .addContainerGap())
        );
        advocateLayout.setVerticalGroup(
            advocateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advocateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(advocate, "card5");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tress Idehen\\Documents\\NetBeansProjects\\PersonalityTest\\images\\mediator.png")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("You Are a: MEDIATOR");

        javax.swing.GroupLayout mediatorLayout = new javax.swing.GroupLayout(mediator);
        mediator.setLayout(mediatorLayout);
        mediatorLayout.setHorizontalGroup(
            mediatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mediatorLayout.createSequentialGroup()
                .addGroup(mediatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mediatorLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addGroup(mediatorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mediatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3))))
                .addContainerGap())
        );
        mediatorLayout.setVerticalGroup(
            mediatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mediatorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(mediator, "card5");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tress Idehen\\Documents\\NetBeansProjects\\PersonalityTest\\images\\protagonist.png")); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("You Are a: PROTAGONIST");

        javax.swing.GroupLayout protagonistLayout = new javax.swing.GroupLayout(protagonist);
        protagonist.setLayout(protagonistLayout);
        protagonistLayout.setHorizontalGroup(
            protagonistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(protagonistLayout.createSequentialGroup()
                .addGroup(protagonistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(protagonistLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addGroup(protagonistLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(protagonistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator4))))
                .addContainerGap())
        );
        protagonistLayout.setVerticalGroup(
            protagonistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(protagonistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(protagonist, "card5");

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tress Idehen\\Documents\\NetBeansProjects\\PersonalityTest\\images\\campaigner.png")); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("You Are a: CAMPAIGNER");

        javax.swing.GroupLayout campaignerLayout = new javax.swing.GroupLayout(campaigner);
        campaigner.setLayout(campaignerLayout);
        campaignerLayout.setHorizontalGroup(
            campaignerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campaignerLayout.createSequentialGroup()
                .addGroup(campaignerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(campaignerLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addGroup(campaignerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(campaignerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator5))))
                .addContainerGap())
        );
        campaignerLayout.setVerticalGroup(
            campaignerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campaignerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(campaigner, "card5");

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tress Idehen\\Documents\\NetBeansProjects\\PersonalityTest\\images\\logistician.png")); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("You Are a: LOGISTICIAN");

        javax.swing.GroupLayout logisticianLayout = new javax.swing.GroupLayout(logistician);
        logistician.setLayout(logisticianLayout);
        logisticianLayout.setHorizontalGroup(
            logisticianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logisticianLayout.createSequentialGroup()
                .addGroup(logisticianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logisticianLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addGroup(logisticianLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(logisticianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator6))))
                .addContainerGap())
        );
        logisticianLayout.setVerticalGroup(
            logisticianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logisticianLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(logistician, "card5");

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tress Idehen\\Documents\\NetBeansProjects\\PersonalityTest\\images\\defender.png")); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("You Are a: DEFENDER");

        javax.swing.GroupLayout defenderLayout = new javax.swing.GroupLayout(defender);
        defender.setLayout(defenderLayout);
        defenderLayout.setHorizontalGroup(
            defenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defenderLayout.createSequentialGroup()
                .addGroup(defenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(defenderLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addGroup(defenderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(defenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator7))))
                .addContainerGap())
        );
        defenderLayout.setVerticalGroup(
            defenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defenderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(defender, "card5");

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tress Idehen\\Documents\\NetBeansProjects\\PersonalityTest\\images\\executive.png")); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("You Are an: EXECUTIVE");

        javax.swing.GroupLayout executiveLayout = new javax.swing.GroupLayout(executive);
        executive.setLayout(executiveLayout);
        executiveLayout.setHorizontalGroup(
            executiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(executiveLayout.createSequentialGroup()
                .addGroup(executiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(executiveLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addGroup(executiveLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(executiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator8))))
                .addContainerGap())
        );
        executiveLayout.setVerticalGroup(
            executiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(executiveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(executive, "card5");

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tress Idehen\\Documents\\NetBeansProjects\\PersonalityTest\\images\\consul.png")); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("You Are a: CONSUL");

        javax.swing.GroupLayout consulLayout = new javax.swing.GroupLayout(consul);
        consul.setLayout(consulLayout);
        consulLayout.setHorizontalGroup(
            consulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consulLayout.createSequentialGroup()
                .addGroup(consulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consulLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addGroup(consulLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(consulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator9))))
                .addContainerGap())
        );
        consulLayout.setVerticalGroup(
            consulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(consul, "card5");

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tress Idehen\\Documents\\NetBeansProjects\\PersonalityTest\\images\\architect.png")); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("You Are an: ARCHITECT");

        javax.swing.GroupLayout architectLayout = new javax.swing.GroupLayout(architect);
        architect.setLayout(architectLayout);
        architectLayout.setHorizontalGroup(
            architectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(architectLayout.createSequentialGroup()
                .addGroup(architectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(architectLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addGroup(architectLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(architectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator10))))
                .addContainerGap())
        );
        architectLayout.setVerticalGroup(
            architectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(architectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(architect, "card5");

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tress Idehen\\Documents\\NetBeansProjects\\PersonalityTest\\images\\logician.png")); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("You Are a: LOGICIAN");

        javax.swing.GroupLayout logicianLayout = new javax.swing.GroupLayout(logician);
        logician.setLayout(logicianLayout);
        logicianLayout.setHorizontalGroup(
            logicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logicianLayout.createSequentialGroup()
                .addGroup(logicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logicianLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addGroup(logicianLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(logicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator11))))
                .addContainerGap())
        );
        logicianLayout.setVerticalGroup(
            logicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logicianLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(logician, "card5");

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tress Idehen\\Documents\\NetBeansProjects\\PersonalityTest\\images\\commander.png")); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("You Are a: COMMANDER");

        javax.swing.GroupLayout commanderLayout = new javax.swing.GroupLayout(commander);
        commander.setLayout(commanderLayout);
        commanderLayout.setHorizontalGroup(
            commanderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commanderLayout.createSequentialGroup()
                .addGroup(commanderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(commanderLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addGroup(commanderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(commanderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator12))))
                .addContainerGap())
        );
        commanderLayout.setVerticalGroup(
            commanderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commanderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(commander, "card5");

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tress Idehen\\Documents\\NetBeansProjects\\PersonalityTest\\images\\debater.png")); // NOI18N

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("You Are a: DEBATER");

        javax.swing.GroupLayout debaterLayout = new javax.swing.GroupLayout(debater);
        debater.setLayout(debaterLayout);
        debaterLayout.setHorizontalGroup(
            debaterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(debaterLayout.createSequentialGroup()
                .addGroup(debaterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(debaterLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addGroup(debaterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(debaterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator13))))
                .addContainerGap())
        );
        debaterLayout.setVerticalGroup(
            debaterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(debaterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(debater, "card5");

        jLabel25.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tress Idehen\\Documents\\NetBeansProjects\\PersonalityTest\\images\\virtuoso.png")); // NOI18N

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("You Are : VIRTUOSO");

        javax.swing.GroupLayout virtuosoLayout = new javax.swing.GroupLayout(virtuoso);
        virtuoso.setLayout(virtuosoLayout);
        virtuosoLayout.setHorizontalGroup(
            virtuosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(virtuosoLayout.createSequentialGroup()
                .addGroup(virtuosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(virtuosoLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addGroup(virtuosoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(virtuosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator14))))
                .addContainerGap())
        );
        virtuosoLayout.setVerticalGroup(
            virtuosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(virtuosoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(virtuoso, "card5");

        jLabel27.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tress Idehen\\Documents\\NetBeansProjects\\PersonalityTest\\images\\adventurer.png")); // NOI18N

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setText("You Are an: ADVENTURER");

        javax.swing.GroupLayout adventurerLayout = new javax.swing.GroupLayout(adventurer);
        adventurer.setLayout(adventurerLayout);
        adventurerLayout.setHorizontalGroup(
            adventurerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adventurerLayout.createSequentialGroup()
                .addGroup(adventurerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adventurerLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addGroup(adventurerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(adventurerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator15))))
                .addContainerGap())
        );
        adventurerLayout.setVerticalGroup(
            adventurerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adventurerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(adventurer, "card5");

        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tress Idehen\\Documents\\NetBeansProjects\\PersonalityTest\\images\\entrepreneur.png")); // NOI18N

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setText("You Are an: ENTREPRENEUR");

        javax.swing.GroupLayout entrepreneurLayout = new javax.swing.GroupLayout(entrepreneur);
        entrepreneur.setLayout(entrepreneurLayout);
        entrepreneurLayout.setHorizontalGroup(
            entrepreneurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entrepreneurLayout.createSequentialGroup()
                .addGroup(entrepreneurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(entrepreneurLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addGroup(entrepreneurLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(entrepreneurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator16))))
                .addContainerGap())
        );
        entrepreneurLayout.setVerticalGroup(
            entrepreneurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entrepreneurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(entrepreneur, "card5");

        jLabel31.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tress Idehen\\Documents\\NetBeansProjects\\PersonalityTest\\images\\entertainer.png")); // NOI18N

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setText("You Are an: ENTERTAINER");

        javax.swing.GroupLayout entertainerLayout = new javax.swing.GroupLayout(entertainer);
        entertainer.setLayout(entertainerLayout);
        entertainerLayout.setHorizontalGroup(
            entertainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entertainerLayout.createSequentialGroup()
                .addGroup(entertainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(entertainerLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addGroup(entertainerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(entertainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator17))))
                .addContainerGap())
        );
        entertainerLayout.setVerticalGroup(
            entertainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entertainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(entertainer, "card5");

        setSize(new java.awt.Dimension(638, 493));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//veryify button function on but display the proceed button and gather user basic info
    private void verify_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verify_userActionPerformed
// TODO add your handling code here:

//this code checkes for the value enters by the user and set's it to the user_fullname variable
// it it also displays the hidden butto that allows the user to progress to the next phase of the application
        
        
        if(input_first_name.getText().equals("") || input_last_name.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Please Enter Name and Last Name!");
        Window_Content.repaint();
    }else {
        verify_user.setEnabled(true);
        user_fullname.setText(input_first_name.getText() +" " + input_last_name.getText());
        welcome_user.setText("Welcome!!!");
        begin_test_button.setVisible(true);
    }
   
    }//GEN-LAST:event_verify_userActionPerformed
//alphabet restriction function key event
    private void NameTypeCheck(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameTypeCheck
                // TODO add your handling code here:
//                this code also restricts the user to simple alphebitical type input
      char c=evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACKSPACE) || c == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_NameTypeCheck
//alphabet restriction key event for lastname entry
    private void input_last_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_last_nameKeyTyped
        // TODO add your handling code here:
//        this code forces the user to only enter alphabetical value by checking to see if anything other than
//          alphabet are written it immediately consumes them!
        char c=evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACKSPACE) || c == KeyEvent.VK_DELETE)){
            evt.consume();
        }
        
        
    }//GEN-LAST:event_input_last_nameKeyTyped
//This is For The Avatar Locator
    private void avatarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avatarMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_avatarMouseClicked

    private void begin_test_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_begin_test_buttonActionPerformed
                // TODO add your handling code here:
        Window_Content.setVisible(false);
        Introduction.setVisible(true);
        Questions.setVisible(false);
        Question1.setText(Question_1);
        Question2.setText(Question_2);
        Question3.setText(Question_3);
        Question4.setText(Question_4);
        Question5.setText(Question_5);
        Question6.setText(Question_6);
        Question7.setText(Question_7);
        Question8.setText(Question_8);
        Question9.setText(Question_9);
        Question10.setText(Question_10);
        Question_Number.setText(Integer.toString(Questionnaire_Location) );
        
    }//GEN-LAST:event_begin_test_buttonActionPerformed

    private void Begin_Test_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Begin_Test_ButtonActionPerformed
        // TODO add your handling code here:
        Introduction.setVisible(false);
        Questions.setVisible(true);
        
        
    }//GEN-LAST:event_Begin_Test_ButtonActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        // TODO add your handling code here:
    
                 
    switch(Questionnaire_Location){
        case 1:
            Total_Points = (Total_Points += Current_Point);
            user_answer.clearSelection();
            Question2.setVisible(true);
            Question1.setVisible(false);
            Questionnaire_Location++; 
            Question_Number.setText(Integer.toString(Questionnaire_Location) );
            break;
        case 2:
            Total_Points = (Total_Points += Current_Point);
            user_answer.clearSelection();
            Question2.setVisible(false);
            Question3.setVisible(true);
            Questionnaire_Location++;
            Question_Number.setText(Integer.toString(Questionnaire_Location) );
            break;
        case 3:
            Total_Points = (Total_Points += Current_Point);
            user_answer.clearSelection();
            Question3.setVisible(false);
            Question4.setVisible(true);
            Questionnaire_Location++; 
            Question_Number.setText(Integer.toString(Questionnaire_Location) );
            break; 
        case 4:
            Total_Points = (Total_Points += Current_Point);
            user_answer.clearSelection();
            Question4.setVisible(false);
            Question5.setVisible(true);
            Questionnaire_Location++;
            Question_Number.setText(Integer.toString(Questionnaire_Location));
            break;
        case 5:
            Total_Points = (Total_Points += Current_Point);
            user_answer.clearSelection();
            Question5.setVisible(false);
            Question6.setVisible(true);
            Questionnaire_Location++;
            Question_Number.setText(Integer.toString(Questionnaire_Location));
            break;
        case 6:
            Total_Points = (Total_Points + Current_Point);
            user_answer.clearSelection();
            Question6.setVisible(false);
            Question7.setVisible(true);
            Questionnaire_Location++;  
            Question_Number.setText(Integer.toString(Questionnaire_Location));
            break;
        case 7:
            Total_Points = (Total_Points += Current_Point);
            user_answer.clearSelection();
            Question7.setVisible(false);
            Question8.setVisible(true);
            Questionnaire_Location++;  
            Question_Number.setText(Integer.toString(Questionnaire_Location));
            break;
        case 8:
            Total_Points = (Total_Points += Current_Point);
            user_answer.clearSelection();
            Question8.setVisible(false);
            Question9.setVisible(true);
            Questionnaire_Location++;   
            Question_Number.setText(Integer.toString(Questionnaire_Location));
            break;
        case 9:
            Total_Points = (Total_Points += Current_Point);
            user_answer.clearSelection();
            Question9.setVisible(false);
            Question10.setVisible(true);
            Questionnaire_Location++;     
            Question_Number.setText(Integer.toString(Questionnaire_Location));
            break;
        case 10:
            Question10.setVisible(false);
            user_response.setVisible(false);
            Question_Title.setVisible(false);
            Question_Number.setVisible(false);
            ProgressBar.setVisible(false);
            ProgressPercentage.setVisible(false);
            Total_Score.setVisible(false);
            Questions.setVisible(false);
            Role_Type_Calculator.setVisible(true);
            break;
     
        } 
    }//GEN-LAST:event_Button1ActionPerformed

    private void strongly_disagreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strongly_disagreeActionPerformed
        // TODO add your handling code here:
        Current_Point = 1;
    }//GEN-LAST:event_strongly_disagreeActionPerformed

    private void disagreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disagreeActionPerformed
        // TODO add your handling code here:
        Current_Point = 2;
    }//GEN-LAST:event_disagreeActionPerformed

    private void indifferentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indifferentActionPerformed
        // TODO add your handling code here:
        Current_Point = 3;
    }//GEN-LAST:event_indifferentActionPerformed

    private void agreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agreeActionPerformed
        // TODO add your handling code here:
        Current_Point = 4;
    }//GEN-LAST:event_agreeActionPerformed

    private void strongly_agreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strongly_agreeActionPerformed
        // TODO add your handling code here:
        Current_Point = 5;
    }//GEN-LAST:event_strongly_agreeActionPerformed

    private void Get_Total_PointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Get_Total_PointActionPerformed
        // TODO add your handling code here:

        
        
        
 if(Total_Points > 0){   
//This is For The Diplomats Personality Types
    //JOptionPane.showMessageDialog(null, Total_Points);
    
         
        if(Total_Points <= 50 && Total_Points > 47){
            Role_Type_Calculator.setVisible(false);
            advocate.setVisible(true);
        }
        
        
        
            else if (Total_Points <= 47 && Total_Points > 44){
                Role_Type_Calculator.setVisible(false);
            mediator.setVisible(true);
        }
        
        
            else if (Total_Points <= 44 && Total_Points > 41){
                Role_Type_Calculator.setVisible(false);
            protagonist.setVisible(true);
        }
       
       
            else if (Total_Points <= 41 && Total_Points > 38){
                Role_Type_Calculator.setVisible(false);
            campaigner.setVisible(true);
        }
      
        
//This is For The Sentinel Personality Types        
     
            else if(Total_Points <= 38 && Total_Points > 35){
                Role_Type_Calculator.setVisible(false);
            logistician.setVisible(true);
        }
   
        
    
            else if(Total_Points <= 35 && Total_Points > 32){
                Role_Type_Calculator.setVisible(false);
            defender.setVisible(true);
        }
    
    
            else if(Total_Points <= 32 && Total_Points > 29){
                Role_Type_Calculator.setVisible(false);
            executive.setVisible(true);
        }
    
        
    
            else if(Total_Points <= 29 && Total_Points > 26){
                Role_Type_Calculator.setVisible(false);
            consul.setVisible(true);
        }
    
    
//This is For The Analysts Personality type
            else if(Total_Points <= 26 && Total_Points > 23){
                Role_Type_Calculator.setVisible(false);
           architect.setVisible(true); 
        }
    
        
    
            else if(Total_Points <= 23 && Total_Points > 20){
                Role_Type_Calculator.setVisible(false);
           logician.setVisible(true); 
        }
    
        
    
            else if(Total_Points <= 20 && Total_Points > 17){
                Role_Type_Calculator.setVisible(false);
           commander.setVisible(true);
        }
    
        
     
            else if(Total_Points <= 17 && Total_Points > 14){
                Role_Type_Calculator.setVisible(false);
           debater.setVisible(true); 
        }
     
        
     
//This is For The Adventurer Role

            else if(Total_Points <= 14 && Total_Points > 11){
                Role_Type_Calculator.setVisible(false);
           virtuoso.setVisible(true); 
        }
    
        
    
            else if(Total_Points <= 11 && Total_Points > 8){
                Role_Type_Calculator.setVisible(false);
           adventurer.setVisible(true);
        }
    
        
    
            else if(Total_Points <= 8 && Total_Points > 5){
                Role_Type_Calculator.setVisible(false);
           entrepreneur.setVisible(true);
        }
       
        
    
            else if(Total_Points <= 5 && Total_Points > 2){
                Role_Type_Calculator.setVisible(false);
           entertainer.setVisible(true); 
        }
    
        
        else{
           JOptionPane.showMessageDialog(null, "Looks Like You Filled In Nothing");
        }
//Button Print Out Window Command:

    }   
 else{
     
 }



        
    }//GEN-LAST:event_Get_Total_PointActionPerformed

    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Begin_Test_Button;
    private javax.swing.JButton Button1;
    private javax.swing.JLabel First_Name;
    private javax.swing.JButton Get_Total_Point;
    private javax.swing.JLabel Instruction_Label;
    private javax.swing.JPanel Introduction;
    private javax.swing.JLabel Last_Name;
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JLabel ProgressPercentage;
    private javax.swing.JLabel Question1;
    private javax.swing.JLabel Question10;
    private javax.swing.JLabel Question2;
    private javax.swing.JLabel Question3;
    private javax.swing.JLabel Question4;
    private javax.swing.JLabel Question5;
    private javax.swing.JLabel Question6;
    private javax.swing.JLabel Question7;
    private javax.swing.JLabel Question8;
    private javax.swing.JLabel Question9;
    private javax.swing.JPanel Question_List;
    private javax.swing.JLabel Question_Number;
    private javax.swing.JLabel Question_Title;
    private javax.swing.JPanel Questions;
    private javax.swing.JPanel Role_Type_Calculator;
    private javax.swing.JSeparator Separator;
    private javax.swing.JSeparator Separator_Instructions;
    private javax.swing.JLabel Total_Score;
    private javax.swing.JPanel Window_Content;
    private javax.swing.JPanel adventurer;
    public javax.swing.JPanel advocate;
    public javax.swing.JRadioButton agree;
    private javax.swing.JPanel architect;
    public javax.swing.JLabel avatar;
    public javax.swing.JButton begin_test_button;
    private javax.swing.JPanel button1;
    private javax.swing.JPanel button_list;
    private javax.swing.JPanel campaigner;
    private javax.swing.JPanel commander;
    private javax.swing.JLabel congratulations;
    private javax.swing.JPanel consul;
    private javax.swing.JPanel debater;
    private javax.swing.JPanel defender;
    public javax.swing.JRadioButton disagree;
    private javax.swing.JPanel entertainer;
    private javax.swing.JPanel entrepreneur;
    private javax.swing.JPanel executive;
    private javax.swing.JLabel header;
    public javax.swing.JRadioButton indifferent;
    public javax.swing.JTextField input_first_name;
    public javax.swing.JTextField input_last_name;
    private javax.swing.JLabel instructions2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JPanel logician;
    private javax.swing.JPanel logistician;
    private javax.swing.JPanel mediator;
    private javax.swing.JPanel protagonist;
    public javax.swing.JRadioButton strongly_agree;
    public javax.swing.JRadioButton strongly_disagree;
    private javax.swing.ButtonGroup user_answer;
    public javax.swing.JLabel user_fullname;
    public javax.swing.JPanel user_response;
    public javax.swing.JButton verify_user;
    private javax.swing.JPanel virtuoso;
    public javax.swing.JLabel welcome_user;
    // End of variables declaration//GEN-END:variables



}
